"""Translates the model.json generated by tensorflowjs_converter from a
Keras 3 .h5 file into the Keras 2 format that tf.loadLayersModel understands.

Usage: python fix_tfjs_keras3.py output/amora_model_tfjs/model.json
"""
import json
import sys


def dtype_to_str(dtype):
    # Keras 3 serializes dtype as a DTypePolicy object; TF.js expects a string
    if isinstance(dtype, dict):
        return dtype.get("config", {}).get("name", "float32")
    return dtype


def collect_tensor_refs(obj, refs):
    """Extract [layer, node_index, tensor_index] from __keras_tensor__ args."""
    if isinstance(obj, dict) and obj.get("class_name") == "__keras_tensor__":
        h = obj["config"]["keras_history"]
        refs.append([h[0], h[1], h[2], {}])
    elif isinstance(obj, (list, tuple)):
        for item in obj:
            collect_tensor_refs(item, refs)


def fix_inbound_nodes(nodes):
    """Keras 3: [{"args": [...], "kwargs": {...}}] -> Keras 2: [[[name, i, j, {}], ...]]"""
    fixed = []
    for node in nodes:
        if isinstance(node, dict):
            refs = []
            collect_tensor_refs(node.get("args", []), refs)
            fixed.append(refs)
        else:  # already in the old format
            fixed.append(node)
    return fixed


def fix_model_json(path):
    with open(path) as f:
        model = json.load(f)

    topo = model["modelTopology"]
    model_config = topo["model_config"]
    config = model_config["config"]

    # TF.js recognizes "Model"; "Functional" is the newer naming
    if model_config.get("class_name") == "Functional":
        model_config["class_name"] = "Model"

    for layer in config["layers"]:
        lc = layer.get("config", {})
        lc["dtype"] = dtype_to_str(lc.get("dtype", "float32"))

        if layer["class_name"] == "InputLayer" and "batch_shape" in lc:
            lc["batch_input_shape"] = lc.pop("batch_shape")

        if "inbound_nodes" in layer:
            layer["inbound_nodes"] = fix_inbound_nodes(layer["inbound_nodes"])

    # input_layers/output_layers: single triple -> list of triples
    for key in ("input_layers", "output_layers"):
        val = config.get(key)
        if isinstance(val, list) and val and isinstance(val[0], str):
            config[key] = [val]

    # Keras 3 saves the DepthwiseConv2D weight as "kernel";
    # TF.js expects "depthwise_kernel"
    depthwise_layers = {
        layer["name"] for layer in config["layers"]
        if layer["class_name"] == "DepthwiseConv2D"
    }
    for group in model.get("weightsManifest", []):
        for weight in group.get("weights", []):
            layer_name, _, weight_name = weight["name"].rpartition("/")
            if layer_name in depthwise_layers and weight_name == "kernel":
                weight["name"] = f"{layer_name}/depthwise_kernel"

    with open(path, "w") as f:
        json.dump(model, f)

    print(f"{path} converted to a TF.js-compatible format")


if __name__ == "__main__":
    fix_model_json(sys.argv[1] if len(sys.argv) > 1 else "output/amora_model_tfjs/model.json")
